@echo off
echo 正在启动后端服务器...
cd backend
echo 检查依赖是否已安装...
pip show fastapi >nul 2>&1
if errorlevel 1 (
    echo 正在安装依赖，请稍候...
    pip install -r requirements.txt
)
echo 启动 FastAPI 服务器...
uvicorn app.main:app --host 0.0.0.0 --port 8000
pause
